services:
  auth:
    container_name: jobbies_auth_pocketbase
    restart: unless-stopped
    build:
      context: ./packages/server/
      dockerfile: Dockerfile.pocketbase
      target: pocketbase
    ports:
      - 8080:8080
    volumes:
      - ./packages/server/pb_data:/pb/pb_data
