services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: jobbies
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

